name: reusable-tag-release

on:
  workflow_call:
    inputs:
      module_dir:
        required: false
        type: string
        default: '.'

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout full repository (fetch tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git user for tagging
        run: |
          git config user.name "github-actions-bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      - name: Install Node and semantic-release
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash
          sudo apt-get install -y nodejs

          npm install --global \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/release-notes-generator \
            @semantic-release/commit-analyzer

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ inputs.module_dir }}
          npx semantic-release
